### ISSUE TITLE
[PA1] Use of Pseudo Instructions (e.g. j, mv, beqz, ...)

### ISSUE THREAD

**Issue by junukwon7** [SNU-ARC/2023_fall_comarch_PA1#1]
Hello, I wonder if we are allowed to use pseudo instructions also provided with the _Green Card_.

I've read the description stating that only RV32I and RV32M are allowed, and was curious if other instructions are disallowed (although being written in the _Green Card_).

For example, using li
```assembly
li x5, 0
```
instead of
```assembly
addi x5, x0, 0
```

**Comment by junukwon7** [comment]
@kjh0615 Thanks for the elaboration!

I've read through your comments, and I fully understand the intentions.

However the provided skeleton code already uses pseudo instructions:

```asm
jr	ra
```

which is in fact equivalent to the line below, as of my knowledge.
```asm
jalr	x0,	ra,	0
```

I'm afraid if there was a slight miscommunication - my question was about pseudo instructions of RV32I/M, not additional instructions like RV32F/A.

Also, while attending the lecture today, I was able to find some more pseudo instructions from the lecture note including `j` from page 95.

I thereby request a clarification for whether or not pseudo instructions are allowed.

Regards,

**Comment by kjh0615** [comment]
we recognized that there were ambiguities in the guidelines and have announced an instruction list that can be used through eTL. Please note that pseudo instructions are not allowed. 
It would be helpful to include content about instructions that would be more useful to use in the write-up

Regards,
Junghoon
