### ISSUE TITLE
Corner Case for Empty Tree (비어 있는 트리에 대한 고려 필요 여부 및 테스트 방법 문의)

### ISSUE THREAD

**Issue by joon0615** [SNU-ARC/2023_fall_comarch_PA1#10]
비어 있는 트리에 대한 경우도 고려해 구현해야 하는지 궁금합니다. 
그리고 만약 고려해야 한다면 어떻게 테스트할 수 있는지도 궁금합니다. 

제가 생각한 테스트 방법은 다음과 같습니다. 
1. 명령어 뒤에 공란으로 두는 경우 
spike --isa=RV32IM /opt/riscv/bin/pk ./tree
해당 형태로 명령어 진행 시 다음과 같은 결과를 얻습니다. 
"Usage: ./tree [val0 val1 val2 ... val14]"

2. 명령어 뒤에 _를 적는 경우
spike --isa=RV32IM /opt/riscv/bin/pk ./tree _
현재 제가 구현한 코드에 이 명령어로 테스트할 경우 -1 값이 나옵니다.

3. 명령어 뒤에 []를 적는 경우
spike --isa=RV32IM /opt/riscv/bin/pk ./tree []
현재 제가 구현한 코드에 이 명령어로 테스트할 경우 0 값이 나옵니다.

**Comment by bgsim** [comment]
안녕하세요. TA 심봉근입니다.

비어있는 트리에 대해서는 고려하지 않으셔도 됩니다.
