### ISSUE TITLE
skeleton 코드 (jr instruction) 및 제출 파일명 관련

### ISSUE THREAD

**Issue by chaeypar** [SNU-ARC/2023_fall_comarch_PA1#13]
안녕하세요,

1)  eTL 공지에서는 RV32I 및 RV32M을 제외한 instruction이 허용되지 않는다고 적혀있었는데요.
주어진 *.s 파일들의 skeleton에는 마지막에 'jr ra'가 있습니다. 해당 부분을 꼭 수정해야 하는지 문의드립니다.
(eTL 공지에 적혀있는 허용되는 instructions에는 jr이 포함되지 않는 것 같습니다.)

2)  더불어, 과제 제출 완료 후 제가 허용되지 않는 instruction을 쓴 것을 발견하여 재제출하였는데요. 
학번이 2023-12345라고 가정하면, 2023-12345.zip 파일을 재제출 했음에도 불구하고 이전에 제출한 기록이 남아있어 2023-12345-1.zip 이라고 뜨는 상황입니다. (파일명 뒤에 -1이 붙습니다.)
이래도 괜찮을까요? 아니면 혹시 -1을 없앨 수 있는 방법이 있는지 문의드립니다.

감사합니다.

**Comment by bgsim** [comment]
1. 아니요, jr ra 는 그대로 두시기 바랍니다. 직접 코드를 짜시는 부분은 해당 부분 윗줄까지입니다. 
2. 네 괜찮습니다. 조교가 파악해서 최신 제출본만 사용하도록 하겠습니다.
감사합니다.
