### ISSUE TITLE
과제 구현 스펙 관련 문의

### ISSUE THREAD

**Issue by kisuk010203** [SNU-ARC/2023_fall_comarch_PA1#15]
조교님 안녕하세요. 구현 중 질문이 생겨서 여쭤봅니다. 
과제 스펙에 별다른 설명 없이 `Compile C source code into Assembly`라고 되어 있는데, 각 C 파일의 코드의 behavior를 그대로 따라가야 하는것인지, 아니면 같은 기능을 수행하는 조금 다른 방법을 짜도 되는지 궁금해서 여쭤봅니다. 

예를 들어, `fibonacci`의 경우 재귀를 사용하라는 언급이 있는데, `tree`의 경우에는 별다른 언급이 없이 Refer to C code라고만 되어 있습니다. 이 경우 BFS가 아닌 DFS를 이용해서 합을 구하였는데, 문제가 있을지 궁금합니다.

감사합니다.

**Comment by bgsim** [comment]
fibonacci는 재귀로 짜셔야하지만 다른 문제는 괜찮습니다.

stack 활용을 정상적으로 잘 하셔서 문제 없이 구현하셨으면 괜찮습니다.

다만 조교의 환경에서 여러 input들을 이용해서 동작시켜보았을 때 문제가 생긴다면 불이익이 있을 수 있습니다.

감사합니다.
