### ISSUE TITLE
PA1 - tree sum : invalid input 고려 여부 관련하여 질문드립니다

### ISSUE THREAD

**Issue by covv09on9** [SNU-ARC/2023_fall_comarch_PA1#16]
problem 03 에서 input은 정상적이라고 가정해도 괜찮을까요? 예를 들어 Null 인 root노드에서 child 노드가 생기는 경우 ( _ 1 1) 이런 input에 대해 예외처리가 되어야 하나요?

**Comment by bgsim** [comment]
정확히는 main에서 tree 만드는 부분을 참고하시면 됩니다. 

root가 null인 경우는 고려하지 않으셔도 됩니다.

감사합니다
