### ISSUE TITLE
[PA1] Issue regarding VirtualBox Download

### ISSUE THREAD

**Issue by RaonDoh** [SNU-ARC/2023_fall_comarch_PA1#2]
Hello. I am a Macbook Apple Silicon user, and I found that VirtualBox no longer support it for apple silicon user.

Then do I have to use other options that you’ve given, or is there any other way to setup the environment?

Thank you.

**Comment by bgsim** [comment]
Please send an email to snu-arc-uarch-ta@googlegroups.com, Then TAs are give you a guide of using Docker.

But, you have to prepare another environment except Mac until further assignment. 

Regards.
