### ISSUE TITLE
레지스터 변수명

### ISSUE THREAD

**Issue by yeonjae11** [SNU-ARC/2023_fall_comarch_PA1#3]
PA1에서 digitsum에서 레지스터 변수를 x5, x6, x7을 이용하여 처음에 코딩을 했을 때는 값이 이상하게 나왔습니다. 그런데 이들을 각각 x18, x19, x20으로 바꾸고 나머지는 그대로 사용하였는데 값이 정상작으로 나오는데 어떤 이유인지 알 수 있을까요?

**Comment by bgsim** [comment]
안녕하세요. TA 심봉근입니다.

정확한 상황을 알 수 없어 명확히 답해드릴 수는 없습니다.
일반적인 경우라면 레지스터변수를 x5,x6,x7을 사용해도 아무 문제 없습니다.
예상해보기로는 해당 레지스터 변수를 다른곳에서 사용하고 있는데 stack에 저장 및 복구 없이 spoil한 경우일 수도 있습니다
다른 경우라면 x5,x6,x7은 다른 이름으로 t0,t1,t2을 사용하고 있습니다. 그렇기때문에 x5와 t0을 중복해서 사용하게되면 문제가 발생할 수 있습니다.

정확한 답변은 드릴 수 없습니다만 종종 발생하는 경우에 대해 답변드렸습니다.
