### ISSUE TITLE
평가 관련 질문

### ISSUE THREAD

**Issue by mingkyun** [SNU-ARC/2023_fall_comarch_PA1#5]
안녕하세요. 이번 과제의 평가 방식과 관련해 궁금한 점이 있어 문의드립니다.

1. 효율적인 코드를 짜야 하는지 궁금합니다.
단순히 C 코드와 동일한 논리의 RISC 코드를 구현만 하면 되는 것인지, 사용한 자원의 양이나 실행 시간 등이 평가 항목에 포함되는지 궁금합니다.
2. Register Use Convention과 비교했을 때 적절하지 않은 레지스터의 사용이 감점 요인이 될 수 있는지 궁금합니다. 

추가로 제가 현재 M2 맥에서 UTM을 사용 중인데, 전에 추후 과제를 위해서는 다른 환경을 준비할 필요가 있다는 조교님의 말씀을 들은 것 같습니다. 이번 과제가 현재 세팅에서는 매우 원활하게 진행됐는데, 추후 나올 과제는 현재의 세팅에서 돌아가지 않을 수도 있을까요?

**Comment by bgsim** [comment]
안녕하세요. 조교 심봉근입니다.

1. 단순히 짜기만 하면 문제없습니다. 숙제에서 기능 외에 요구하는 사항이 있다면 미리 공지하도록 하겠습니다.
2. 정상동작한다면 일단은 문제없도록 할 것입니다.다만 평가 환경은 조교의 환경에서 평가할 예정이고 동작시 input도 다양하게 줄 예정이므로 다양한 고려가 필요합니다.
3. 네 학기중 맥에서는 동작시키기 어려울 것으로 예상되는 과제가 나갈 예정입니다. 

감사합니다
