### ISSUE TITLE
Problem regarding VirtualBox Download in Linux

### ISSUE THREAD

**Issue by RaonDoh** [SNU-ARC/2023_fall_comarch_PA1#6]
안녕하세요. 

UTM을 활용하여 Linux에서 virtualbox를 다운로드하는 과정에서 문제가 발생하여 질문 드립니다.

<img width="1440" alt="스크린샷 2023-09-24 오후 4 58 45" src="https://github.com/SNU-ARC/2023_fall_comarch_PA1/assets/131836818/7995bb01-44b9-4e98-a026-e696f8052cf6">

위의 이미지에서 확인할 수 있듯, 관련 문제를 구글링해보았으나 별다른 해결을 얻지 못하였습니다. 이에 조금이나마 도움을 얻고자 질문 드립니다. (혹 경로 관련 이슈일지 모르겠습니다.)

감사합니다.

**Comment by Jong25** [comment]
우선 mac 환경은 저희가 지원하지 않아 답변이 정확하기 않을 수 있다는 점 양해 바랍니다.

올려주신 캡쳐로 판단하기에 이미 UTM으로 제공한 우분투 이미지 부팅에 성공하신 것으로 보입니다. 해당 환경에서 과제 바로 수행하시면 될 것으로 생각됩니다.

virtualbox 설치가 필요하시다면 다음 command 활용하시기 바랍니다.

```
sudo apt update && sudo apt upgrade # update package list && upgrade installed packages
sudo apt install virtualbox
```

**Comment by choco-bear** [comment]
Is it okay to touch the code in a place other than between following comments?
```
	#------Your code starts here------
	# root tree node addr : a0, queue array addr : a1

	# Load return value to reg a0
	#------Your code ends here------
```
For example, is it okay to add some lines like `.eqv sum t0` in the preamble of the assembly code?
