### ISSUE TITLE
Modification of the preamble

### ISSUE THREAD

**Issue by choco-bear** [SNU-ARC/2023_fall_comarch_PA1#7]
Is it okay to touch the code in a place other than between following comments?
```
	#------Your code starts here------
	# root tree node addr : a0, queue array addr : a1

	# Load return value to reg a0
	#------Your code ends here------
```
For example, is it okay to add some lines like `.eqv sum t0` in the preamble of the assembly code?

**Comment by bgsim** [comment]
No, you don't.

Please follow guided notice in advance, use RV32i and RV32m only.
If not, you could get disadvantage.

regards.
