### ISSUE TITLE
User segfault

### ISSUE THREAD

**Issue by SeongjunJo** [SNU-ARC/2023_fall_comarch_PA1#8]
과제를 진행하던 도중 User fetch/store segfault가 도무지 해결되지 않아서 질문 드립니다.
질의를 할 수 있도록 과제 관련 코드가 아닌, lecture 2 강의 노트 62 page의 코드를 test 해보았습니다.
run.sh 파일에서 input을 1로 조정하여서, 예상되는 결과는 L1을 거치지 않고 결과가 1이 나올 것으로 기대하였으나, 나온 결과는 L1을 거치고 12라는 값이 나왔습니다.
동시에 User fetch segfault 에러도 해결되지 않아, 제가 수업 내용을 잘 이해하지 못한 것인지 아니면 외적인 문제인지 여쭤보고 싶습니다.

![image](https://github.com/SNU-ARC/2023_fall_comarch_PA1/assets/114854099/dcbdfbb2-fc03-451b-85e9-43f1dbebe9aa)
![image](https://github.com/SNU-ARC/2023_fall_comarch_PA1/assets/114854099/27c18054-f828-416b-b3f4-f92949d93c73)

**Comment by bgsim** [comment]
안녕하세요. 조교 심봉근입니다.

제가 여기서 정답을 알려드리면 형평성에 어긋나기 때문에 답을 알려드릴 수는 없습니다.

다만 말씀드릴 수 있는것은 현재 학생분코드는 L1을 거치고 12가 나오며 동시에 user segfault가 발생하도록 코드가 작성되어있습니다.

수업 ppt와 더불어 제공해드린 risc-v instruction guide를 잘 참조해주시기 바랍니다.

감사합니다.
