### ISSUE TITLE
Nicknames of registers

### ISSUE THREAD

**Issue by mahoon2** [SNU-ARC/2023_fall_comarch_PA1#9]
안녕하세요. 이번 과제에서는 Pseudoinstruction의 사용이 금지된 것으로 아는데, 그렇다면 레지스터 또한 오로지 x0~x31 로만 지칭하고 ra, a0, a1 등의 별칭을 쓰면 안 되는 것일까요?

추가로, 현재 --with-arch=rv32im --with-abi=ilp32 옵션으로 세팅이 되어있는 것 같은데, 이 세팅이 추후 과제에서도 유지되는지 궁금합니다(즉 앞으로도 동일하게 32비트를 가정하면 되는지).

**Comment by bgsim** [comment]
1. register는 전혀 문제없습니다. 어떤 것이든 사용해도 상관 없으며 다만 문제만 없게끔 하시면 됩니다.
2. 앞으로도 32bit 를 가정하고 있습니다. 다만 RV32im 에 ilp32 옵션은 아닐 수 있습니다. 
감사합니다.
